RE_WEAPON = r'^(tf_weapon_[a-zA-Z_]+)\.txt$'
RE_HEADER = r'^\s*(\"?[a-zA-Z0-9\_\.\#]+\"?)\s*({)?$'
RE_DATA = r'^\s*\"?([^\s\"{}]+)\"?\s+\"?([^\s\"{}]+)\"?$'
RE_BRACKET_OPEN = r'^\s*{\s*$'
RE_BRACKET_CLOSE = r'^\s*}\s*$'
RE_COMMENT = r'^\s*\/\/(.+)$'